export const USER_CONST = {
  NAME_MAX_LENGTH: 256,
  PHONE_NUMBER_MAX_LENGTH: 20,
  USERNAME_MIN_LENGTH: 4,
  USERNAME_MAX_LENGTH: 64,
  PASSWORD_MIN_LENGTH: 4,
  PASSWORD_MAX_LENGTH: 128,
  EMAIL_MAX_LENGTH: 512,
  TOKEN_MAX_LENGTH: 256,
};

export const USER_MODEL = 'users';

export const BCRYPT_HASH_NUMBER = 10;
